# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/BlazeTop.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_microblaze_0_0/system_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_microblaze_0_0 || ORIG_REF_NAME==system_microblaze_0_0} -quiet] -quiet

# IP: bd/system/ip/system_dlmb_v10_1/system_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dlmb_v10_1 || ORIG_REF_NAME==system_dlmb_v10_1} -quiet] -quiet

# IP: bd/system/ip/system_ilmb_v10_1/system_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ilmb_v10_1 || ORIG_REF_NAME==system_ilmb_v10_1} -quiet] -quiet

# IP: bd/system/ip/system_dlmb_bram_if_cntlr_1/system_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==system_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/system/ip/system_ilmb_bram_if_cntlr_1/system_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==system_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/system/ip/system_lmb_bram_1/system_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_lmb_bram_1 || ORIG_REF_NAME==system_lmb_bram_1} -quiet] -quiet

# IP: bd/system/ip/system_xbar_1/system_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1} -quiet] -quiet

# IP: bd/system/ip/system_microblaze_0_axi_periph_1/system_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_periph_1 || ORIG_REF_NAME==system_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/system/ip/system_microblaze_0_axi_intc_1/system_microblaze_0_axi_intc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_intc_1 || ORIG_REF_NAME==system_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/system/ip/system_microblaze_0_xlconcat_1/system_microblaze_0_xlconcat_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_microblaze_0_xlconcat_1 || ORIG_REF_NAME==system_microblaze_0_xlconcat_1} -quiet] -quiet

# IP: bd/system/ip/system_mdm_1_1/system_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_mdm_1_1 || ORIG_REF_NAME==system_mdm_1_1} -quiet] -quiet

# IP: bd/system/ip/system_rst_Clk_100M_1/system_rst_Clk_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_Clk_100M_1 || ORIG_REF_NAME==system_rst_Clk_100M_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_uartlite_0_0 || ORIG_REF_NAME==system_axi_uartlite_0_0} -quiet] -quiet

# XDC: c:/Harman/Verilog/SoC_06_23_LED_Counter/SoC_06_23_LED_Counter.gen/sources_1/bd/system/system_ooc.xdc
