# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Harman/Verilog/SoC_06_20_blaze_w5500/SoC_06_20_blaze_w5500.srcs/sources_1/bd/system/ip/system_xbar_1/system_xbar_1.xci
# IP: The module: 'system_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Harman/Verilog/SoC_06_20_blaze_w5500/SoC_06_20_blaze_w5500.gen/sources_1/bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Harman/Verilog/SoC_06_20_blaze_w5500/SoC_06_20_blaze_w5500.srcs/sources_1/bd/system/ip/system_xbar_1/system_xbar_1.xci
# IP: The module: 'system_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Harman/Verilog/SoC_06_20_blaze_w5500/SoC_06_20_blaze_w5500.gen/sources_1/bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
