# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Harman/Verilog/SoC_06_19_UI/SoC_06_19_UI.srcs/sources_1/bd/mb1/ip/mb1_xbar_0/mb1_xbar_0.xci
# IP: The module: 'mb1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Harman/Verilog/SoC_06_19_UI/SoC_06_19_UI.gen/sources_1/bd/mb1/ip/mb1_xbar_0/mb1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb1_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Harman/Verilog/SoC_06_19_UI/SoC_06_19_UI.srcs/sources_1/bd/mb1/ip/mb1_xbar_0/mb1_xbar_0.xci
# IP: The module: 'mb1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Harman/Verilog/SoC_06_19_UI/SoC_06_19_UI.gen/sources_1/bd/mb1/ip/mb1_xbar_0/mb1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb1_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
