# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Harman/Verilog/SoC_06_13/SoC_06_13.srcs/sources_1/ip/sdpram1/sdpram1.xci
# IP: The module: 'sdpram1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Harman/Verilog/SoC_06_13/SoC_06_13.gen/sources_1/ip/sdpram1/sdpram1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sdpram1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Harman/Verilog/SoC_06_13/SoC_06_13.srcs/sources_1/ip/sdpram1/sdpram1.xci
# IP: The module: 'sdpram1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Harman/Verilog/SoC_06_13/SoC_06_13.gen/sources_1/ip/sdpram1/sdpram1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sdpram1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
