# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Harman/Lecture Files/Verilog_RTL Design/digilent-xdc-master/Basys-3-Master.xdc

# Block Designs: bd/spi_con_exam_IP/spi_con_exam_IP.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_con_exam_IP || ORIG_REF_NAME==spi_con_exam_IP} -quiet] -quiet

# IP: bd/spi_con_exam_IP/ip/spi_con_exam_IP_top_fndcontrol2_0_0/spi_con_exam_IP_top_fndcontrol2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_con_exam_IP_top_fndcontrol2_0_0 || ORIG_REF_NAME==spi_con_exam_IP_top_fndcontrol2_0_0} -quiet] -quiet

# IP: bd/spi_con_exam_IP/ip/spi_con_exam_IP_clk_wiz_0/spi_con_exam_IP_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_con_exam_IP_clk_wiz_0 || ORIG_REF_NAME==spi_con_exam_IP_clk_wiz_0} -quiet] -quiet

# IP: bd/spi_con_exam_IP/ip/spi_con_exam_IP_rst_clk_wiz_100M_0/spi_con_exam_IP_rst_clk_wiz_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_con_exam_IP_rst_clk_wiz_100M_0 || ORIG_REF_NAME==spi_con_exam_IP_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/spi_con_exam_IP/ip/spi_con_exam_IP_reset_inv_0_0/spi_con_exam_IP_reset_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_con_exam_IP_reset_inv_0_0 || ORIG_REF_NAME==spi_con_exam_IP_reset_inv_0_0} -quiet] -quiet

# XDC: c:/Harman/Verilog/SoC_06_16_prac/SoC_06_16_prac.gen/sources_1/bd/spi_con_exam_IP/spi_con_exam_IP_ooc.xdc
