# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Harman/Verilog/SoC_06_21_BM_Interface/SoC_06_21_BM_Interface.srcs/sources_1/bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xci
# IP: The module: 'system_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Harman/Verilog/SoC_06_21_BM_Interface/SoC_06_21_BM_Interface.gen/sources_1/bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Harman/Verilog/SoC_06_21_BM_Interface/SoC_06_21_BM_Interface.gen/sources_1/bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Harman/Verilog/SoC_06_21_BM_Interface/SoC_06_21_BM_Interface.gen/sources_1/bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Harman/Verilog/SoC_06_21_BM_Interface/SoC_06_21_BM_Interface.srcs/sources_1/bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xci
# IP: The module: 'system_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Harman/Verilog/SoC_06_21_BM_Interface/SoC_06_21_BM_Interface.gen/sources_1/bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Harman/Verilog/SoC_06_21_BM_Interface/SoC_06_21_BM_Interface.gen/sources_1/bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Harman/Verilog/SoC_06_21_BM_Interface/SoC_06_21_BM_Interface.gen/sources_1/bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
