# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/basys-3.xdc

# Block Designs: bd/servo/servo.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==servo || ORIG_REF_NAME==servo} -quiet] -quiet

# IP: bd/servo/ip/servo_servo_axi_0_4/servo_servo_axi_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==servo_servo_axi_0_4 || ORIG_REF_NAME==servo_servo_axi_0_4} -quiet] -quiet

# IP: bd/servo/ip/servo_microblaze_0_1/servo_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==servo_microblaze_0_1 || ORIG_REF_NAME==servo_microblaze_0_1} -quiet] -quiet

# IP: bd/servo/ip/servo_axi_uartlite_0_1/servo_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==servo_axi_uartlite_0_1 || ORIG_REF_NAME==servo_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/servo/ip/servo_axi_gpio_0_1/servo_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==servo_axi_gpio_0_1 || ORIG_REF_NAME==servo_axi_gpio_0_1} -quiet] -quiet

# IP: bd/servo/ip/servo_dlmb_v10_1/servo_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==servo_dlmb_v10_1 || ORIG_REF_NAME==servo_dlmb_v10_1} -quiet] -quiet

# IP: bd/servo/ip/servo_ilmb_v10_1/servo_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==servo_ilmb_v10_1 || ORIG_REF_NAME==servo_ilmb_v10_1} -quiet] -quiet

# IP: bd/servo/ip/servo_dlmb_bram_if_cntlr_1/servo_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==servo_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==servo_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/servo/ip/servo_ilmb_bram_if_cntlr_1/servo_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==servo_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==servo_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/servo/ip/servo_lmb_bram_1/servo_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==servo_lmb_bram_1 || ORIG_REF_NAME==servo_lmb_bram_1} -quiet] -quiet

# IP: bd/servo/ip/servo_mdm_1_1/servo_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==servo_mdm_1_1 || ORIG_REF_NAME==servo_mdm_1_1} -quiet] -quiet

# IP: bd/servo/ip/servo_clk_wiz_1_1/servo_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==servo_clk_wiz_1_1 || ORIG_REF_NAME==servo_clk_wiz_1_1} -quiet] -quiet

# IP: bd/servo/ip/servo_rst_clk_wiz_1_100M_1/servo_rst_clk_wiz_1_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==servo_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==servo_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/servo/ip/servo_xbar_0/servo_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==servo_xbar_0 || ORIG_REF_NAME==servo_xbar_0} -quiet] -quiet

# IP: bd/servo/ip/servo_microblaze_0_axi_periph_0/servo_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==servo_microblaze_0_axi_periph_0 || ORIG_REF_NAME==servo_microblaze_0_axi_periph_0} -quiet] -quiet

# XDC: c:/Harman/Verilog/SoC_07_23_servo_axi/SoC_07_23_servo_axi.gen/sources_1/bd/servo/servo_ooc.xdc
