# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Harman/Verilog/SoC_06_23_LED_Counter/SoC_06_23_LED_Counter.srcs/sources_1/bd/system/ip/system_dlmb_bram_if_cntlr_1/system_dlmb_bram_if_cntlr_1.xci
# IP: The module: 'system_dlmb_bram_if_cntlr_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Harman/Verilog/SoC_06_23_LED_Counter/SoC_06_23_LED_Counter.gen/sources_1/bd/system/ip/system_dlmb_bram_if_cntlr_1/system_dlmb_bram_if_cntlr_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_dlmb_bram_if_cntlr_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Harman/Verilog/SoC_06_23_LED_Counter/SoC_06_23_LED_Counter.srcs/sources_1/bd/system/ip/system_dlmb_bram_if_cntlr_1/system_dlmb_bram_if_cntlr_1.xci
# IP: The module: 'system_dlmb_bram_if_cntlr_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Harman/Verilog/SoC_06_23_LED_Counter/SoC_06_23_LED_Counter.gen/sources_1/bd/system/ip/system_dlmb_bram_if_cntlr_1/system_dlmb_bram_if_cntlr_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_dlmb_bram_if_cntlr_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
