# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Harman/Verilog/SoC_06_16_prac/SoC_06_16_prac.srcs/sources_1/bd/spi_con_exam_IP/ip/spi_con_exam_IP_clk_wiz_0/spi_con_exam_IP_clk_wiz_0.xci
# IP: The module: 'spi_con_exam_IP_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Harman/Verilog/SoC_06_16_prac/SoC_06_16_prac.gen/sources_1/bd/spi_con_exam_IP/ip/spi_con_exam_IP_clk_wiz_0/spi_con_exam_IP_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_con_exam_IP_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Harman/Verilog/SoC_06_16_prac/SoC_06_16_prac.gen/sources_1/bd/spi_con_exam_IP/ip/spi_con_exam_IP_clk_wiz_0/spi_con_exam_IP_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_con_exam_IP_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Harman/Verilog/SoC_06_16_prac/SoC_06_16_prac.gen/sources_1/bd/spi_con_exam_IP/ip/spi_con_exam_IP_clk_wiz_0/spi_con_exam_IP_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_con_exam_IP_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Harman/Verilog/SoC_06_16_prac/SoC_06_16_prac.srcs/sources_1/bd/spi_con_exam_IP/ip/spi_con_exam_IP_clk_wiz_0/spi_con_exam_IP_clk_wiz_0.xci
# IP: The module: 'spi_con_exam_IP_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Harman/Verilog/SoC_06_16_prac/SoC_06_16_prac.gen/sources_1/bd/spi_con_exam_IP/ip/spi_con_exam_IP_clk_wiz_0/spi_con_exam_IP_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_con_exam_IP_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Harman/Verilog/SoC_06_16_prac/SoC_06_16_prac.gen/sources_1/bd/spi_con_exam_IP/ip/spi_con_exam_IP_clk_wiz_0/spi_con_exam_IP_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_con_exam_IP_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Harman/Verilog/SoC_06_16_prac/SoC_06_16_prac.gen/sources_1/bd/spi_con_exam_IP/ip/spi_con_exam_IP_clk_wiz_0/spi_con_exam_IP_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_con_exam_IP_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
