# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Harman/Verilog/SoC_06_23_HelloWorld/SoC_06_23_HelloWorld.srcs/sources_1/bd/mb1/ip/mb1_mdm_1_0/mb1_mdm_1_0.xci
# IP: The module: 'mb1_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Harman/Verilog/SoC_06_23_HelloWorld/SoC_06_23_HelloWorld.gen/sources_1/bd/mb1/ip/mb1_mdm_1_0/mb1_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb1_mdm_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Harman/Verilog/SoC_06_23_HelloWorld/SoC_06_23_HelloWorld.gen/sources_1/bd/mb1/ip/mb1_mdm_1_0/mb1_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb1_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Harman/Verilog/SoC_06_23_HelloWorld/SoC_06_23_HelloWorld.srcs/sources_1/bd/mb1/ip/mb1_mdm_1_0/mb1_mdm_1_0.xci
# IP: The module: 'mb1_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Harman/Verilog/SoC_06_23_HelloWorld/SoC_06_23_HelloWorld.gen/sources_1/bd/mb1/ip/mb1_mdm_1_0/mb1_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb1_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Harman/Verilog/SoC_06_23_HelloWorld/SoC_06_23_HelloWorld.gen/sources_1/bd/mb1/ip/mb1_mdm_1_0/mb1_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb1_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
