# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Harman/Verilog/SoC_07_23_servo_axi/SoC_07_23_servo_axi.srcs/sources_1/bd/servo/ip/servo_dlmb_v10_1/servo_dlmb_v10_1.xci
# IP: The module: 'servo_dlmb_v10_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Harman/Verilog/SoC_07_23_servo_axi/SoC_07_23_servo_axi.gen/sources_1/bd/servo/ip/servo_dlmb_v10_1/servo_dlmb_v10_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'servo_dlmb_v10_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Harman/Verilog/SoC_07_23_servo_axi/SoC_07_23_servo_axi.srcs/sources_1/bd/servo/ip/servo_dlmb_v10_1/servo_dlmb_v10_1.xci
# IP: The module: 'servo_dlmb_v10_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Harman/Verilog/SoC_07_23_servo_axi/SoC_07_23_servo_axi.gen/sources_1/bd/servo/ip/servo_dlmb_v10_1/servo_dlmb_v10_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'servo_dlmb_v10_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
