# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Harman/Verilog/SoC_07_23_servo_axi/SoC_07_23_servo_axi.srcs/sources_1/bd/servo/ip/servo_xbar_0/servo_xbar_0.xci
# IP: The module: 'servo_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Harman/Verilog/SoC_07_23_servo_axi/SoC_07_23_servo_axi.gen/sources_1/bd/servo/ip/servo_xbar_0/servo_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'servo_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Harman/Verilog/SoC_07_23_servo_axi/SoC_07_23_servo_axi.srcs/sources_1/bd/servo/ip/servo_xbar_0/servo_xbar_0.xci
# IP: The module: 'servo_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Harman/Verilog/SoC_07_23_servo_axi/SoC_07_23_servo_axi.gen/sources_1/bd/servo/ip/servo_xbar_0/servo_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'servo_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
