# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Harman/Lecture Files/Verilog_RTL Design/digilent-xdc-master/Basys-3-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_top_fndcontrol2_0_0/design_1_top_fndcontrol2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_top_fndcontrol2_0_0 || ORIG_REF_NAME==design_1_top_fndcontrol2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0 || ORIG_REF_NAME==design_1_clk_wiz_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_clk_wiz_100M_0/design_1_rst_clk_wiz_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reset_inv_0_0/design_1_reset_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reset_inv_0_0 || ORIG_REF_NAME==design_1_reset_inv_0_0} -quiet] -quiet

# XDC: c:/Harman/Verilog/SoC_06_17_NEWIP/SoC_06_17_NEWIP.gen/sources_1/bd/design_1/design_1_ooc.xdc
