# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Harman/Verilog/SoC_07_15_blaze_w5500_rev/SoC_07_15_blaze_w5500_rev.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
# IP: The module: 'system_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Harman/Verilog/SoC_07_15_blaze_w5500_rev/SoC_07_15_blaze_w5500_rev.gen/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_pc_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Harman/Verilog/SoC_07_15_blaze_w5500_rev/SoC_07_15_blaze_w5500_rev.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
# IP: The module: 'system_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Harman/Verilog/SoC_07_15_blaze_w5500_rev/SoC_07_15_blaze_w5500_rev.gen/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_pc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
